spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
#  cloud:
#    config:
#      server:
#         native:
#          search-locations: "classpath:/config"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/AryanJindal7/spring-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true




#        native:
#          search-locations: "classpath:/config"

#         search-locations: ""
    refresh:
      enabled: false

#encrypt:
#  key: 11BBXMJ3Y0sJjh4a7n60Kh_rrZhrhK1198EHbWEjLDsGKxm0RqSZFlTgdoqFBFfKfDKRXEC7POV3rcpYP1
server:
  port: 8071
